//require('./stylesheets/base.scss')
//define(['require-css!./stylesheets/base.css'], function() {});

// require('./images/tech-radar-landing-page-wide.png')
// require('./images/tw-logo.png')
// require('./images/favicon.ico')
// require('./images/search-logo-2x.svg')
// require('./images/new.svg')
// require('./images/existing.svg')
// require('./images/arrow-icon.svg')
// require('./images/first-quadrant-btn-bg.svg')
// require('./images/second-quadrant-btn-bg.svg')
// require('./images/third-quadrant-btn-bg.svg')
// require('./images/fourth-quadrant-btn-bg.svg')
// require('./images/arrow-white-icon.svg')
// require('./images/search-active-wave.svg')
// require('./images/pdf_banner.png')
